### ISSUE TITLE
Minimize

### ISSUE THREAD

**Issue by Cortez2002** [1Kxhu/CuoreUI#11]
Hi!
When i try to minimize i get the program laying down at the windows search as a bar (At_Minimize).
![At_minimize](https://github.com/user-attachments/assets/b3791a19-d9da-4936-8864-0382a9d637b6)

Then i do maximize again and form shows but it is all black without visible controls, i need to press the icon at the taskbar to get the controls back.
(I use cuiFormRounder and cuiFormDrag)

I use Windows 10, updated Visual studio 2022 and <TargetFramework>net8.0-windows</TargetFramework>

It also seems like i get an exception when i exit program in debug, that is followed with an an error message when i press continue on the exception.

![Exception](https://github.com/user-attachments/assets/98f19de9-e12c-4c59-a711-705562e27460)
![MVS_Error](https://github.com/user-attachments/assets/f57f1cd1-e741-4a8d-86c3-7b6c6476728d)

First text in exception:
Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CuoreUI.Components.cuiFormRounder.TargetForm_VisibleChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.DotNet.DesignTools.Frame.DesignerWindowFrame.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

Thanx
Torbjørn

**Comment by 1Kxhu** [comment]
i'll look into it soon

**Comment by 1Kxhu** [comment]
i seem to have fixed the bug, coming in next release soon
![1232938714020450345](https://github.com/user-attachments/assets/26afbec6-83dd-479b-ae00-a48574e0ffd1)

**Comment by Cortez2002** [comment]
Super, ty for your time!
